### ISSUE TITLE
Duplicate Numbers

### ISSUE THREAD

**Issue by evripidesk** [lukasgit/flutter_contacts#175] opened 2020-12-10 10:53 UTC
Hello

Some android devices when fetch the contacts show duplicate numbers under one contact

**Comment by doublej74** [comment] 2020-12-14 10:15
I encounter the same problem and trying to figure out what is going on. I get two contacts with the same phone number and name. Initially I had the feeling that this only happens to merged contacts. however, I just tested it and this is not the case. I continue to see if I can find the cause.

**Comment by Alloco225** [comment] 2021-01-06 06:58
I think the duplicate phone numbers come from other apps that have write permission to the contacts, apps like whatsapp, whatsapp business, telegram and the likes. They most likely store a duplicate (sometimes formatted) version of the same phone number on the contact. So if one contact is registered in the 3 above apps for example it will probably have 3 duplicate versions of each phone number used by said apps.

**Closed** 2021-03-14 14:41 UTC
Labels: wontfix
