### ISSUE TITLE
ie: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid envelope

### ISSUE THREAD

**Issue by Rajeshhmuthyala** [lukasgit/flutter_contacts#60] opened 2019-11-13 05:52 UTC
await ContactsService.addContact(Contact(
     givenName: contactdetails.Firstname,
     phones: [phoneNumber]
   ));

**Comment by COCPORN** [comment] 2019-11-30 15:41
I am getting the same issue. Let me know if you need help to reproduce.

**Comment by hsult4n** [comment] 2019-12-08 19:25
Same problem here!!

**Comment by lukasgit** [comment] 2019-12-21 19:19
@Rajeshhmuthyala @COCPORN @hsult4n please post steps / code to reproduce. Thanks

**Comment by COCPORN** [comment] 2019-12-22 16:51
Disclaimer: I am totally new to flutter. I can provide a full repo that compiles and runs, but this here is the offending code:

```
  void _saveNumber() {
    debugPrint('Saving number ${numberController.text}'); 
    PostalAddress address = PostalAddress(label: "Home");
    Contact contact = Contact(
      displayName: nameController.text,
      givenName: nameController.text,
      phones: [Item(label: 'mobile', value: numberController.text)],
      postalAddresses: [address]      
    );
    ContactsService.addContact(contact);
    setState(() {
      numberController.text = '';
      nameController.text = '';
    });
  }
```

**Comment by Sthefanny** [comment] 2020-01-02 16:00
same problem... any solutions?

**Comment by AndreyMolochko** [comment] 2020-01-23 11:08
The same problem

**Comment by AndreyMolochko** [comment] 2020-01-24 06:45
I had the same problem. For solving this problem you should apply permissions on write data in contacts. It's a dangerous permissions, so add permission only in manifest is not enough. For call window applying or dinying permissions you can use permission_handler 4.2.0 .

await PermissionHandler().requestPermissions([PermissionGroup.contacts]);

After calling this method you can apply permission and contact will be added. By the way, this solution is needed only for android devices with Android 6.0 (API level 23) or higher. In lower versions you apply all permissions, when install your app.

**Comment by isojtouano** [comment] 2020-02-27 00:48
@AndreyMolochko 's answer worked for me, thanks!

**Comment by lukasgit** [comment] 2020-04-22 05:19
https://github.com/lukasgit/flutter_contacts/issues/60#issuecomment-578011954 looks like the working solution here. Closing this issue.

**Closed by lukasgit** 2020-04-22 05:19 UTC
Labels: question
